createCoffee:
  handler: src/handlers/createCoffee.handler
  events:
    - http:
        path: /coffee
        method: post
        cors: true
        request:
          schemas:
            application/json: ${file(src/models/createCoffeeRequest.json)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt: [CoffeeTable, Arn]

listCoffees:
  handler: src/handlers/listCoffees.handler
  events:
    - http:
        path: /coffee
        method: get
        cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        - Fn::GetAtt: [CoffeeTable, Arn]

getCoffee:
  handler: src/handlers/getCoffee.handler
  events:
    - http:
        path: /coffee/{id}
        method: get
        cors: true
        request:
          parameters:
            paths:
              id: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - Fn::GetAtt: [CoffeeTable, Arn]

deleteCoffee:
  handler: src/handlers/deleteCoffee.handler
  events:
    - http:
        path: /coffee/{id}
        method: delete
        cors: true
        request:
          parameters:
            paths:
              id: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::GetAtt: [CoffeeTable, Arn]

updateCoffee:
  handler: src/handlers/updateCoffee.handler
  events:
    - http:
        path: /coffee/{id}
        method: put
        cors: true
        request:
          parameters:
            paths:
              id: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - Fn::GetAtt: [CoffeeTable, Arn]
