org: mohsinsheikhani
app: coffee-shop-api

service: coffee-shop-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    COFFEE_TABLE: ${self:service}-${self:provider.stage}-coffee
    STAGE: ${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

package:
  individually: true

functions: ${file(config/functions.yml)}

resources:
  Resources:
    CoffeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.COFFEE_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}

  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: ${self:service}-${self:provider.stage}-ApiGatewayRestApiId

    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: ${self:service}-${self:provider.stage}-ApiGatewayRestApiRootResourceId

    CoffeeTableName:
      Value:
        Ref: CoffeeTable
      Export:
        Name: ${self:service}-${self:provider.stage}-CoffeeTableName
